apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tls-notifier-admin
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-view
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: tls-notifier-admin
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tls-notifier
  name: tls-notifier
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tls-notifier
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tls-notifier
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: notifier-config
          image: regoo707/tls-notifier:beta
          imagePullPolicy: Always
          name: tls-notifier